// Refreshes src/ocado-products.js: for every ingredient in the shopping dictionary,
// queries Ocado's product-search API, picks the best-matching product (M&S brand
// preferred) and records title, pack size, price and link. Run with: npm run ocado
// One request per ingredient with a polite pause — takes about a minute.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { OCADO_ITEMS, packGrams } from '../src/ocado.js';

const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';
const PAUSE_MS = 800;
const sleep = ms => new Promise(r => setTimeout(r, ms));

// Same search API the Ocado site itself uses; public, no login needed.
async function searchApi(phrase) {
  const qs = new URLSearchParams({ q: phrase, tag: 'web', maxProductsToDecorate: '12', maxPageSize: '20' });
  const url = `https://www.ocado.com/api/webproductpagews/v6/product-pages/search?${qs}`;
  for (let attempt = 1; attempt <= 2; attempt++) {
    try {
      const res = await fetch(url, { headers: { 'User-Agent': UA, Accept: 'application/json' } });
      if (res.ok) return await res.json();
      console.error(`  HTTP ${res.status} for "${phrase}"`);
    } catch (e) {
      console.error(`  fetch failed for "${phrase}": ${e.message}`);
    }
    await sleep(3000);
  }
  return null;
}

const productUrl = p => {
  const slug = p.name.toLowerCase().replace(/&/g, ' ').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return `https://www.ocado.com/products/${slug}/${p.retailerProductId}`;
};

// Returns qualifying candidates ranked best-first (score, then cheaper per unit).
// [0] is the pick; the next two become swap alternatives in the app.
function pickRanked(data, item, requireOrganic = false) {
  const candidates = (data?.productGroups || []).flatMap(g => g.decoratedProducts || []);
  const unitAmt = p => Number(p.unitPrice?.price?.amount) || Infinity;
  const scored = [];
  for (const p of candidates) {
    if (!p.available || !p.price?.amount) continue;
    const name = p.name.toLowerCase();
    if (requireOrganic && !name.includes('organic')) continue;
    if (!item.must.every(group => group.split('|').some(tok => name.includes(tok)))) continue;
    if (item.not?.some(group => group.split('|').some(tok => name.includes(tok)))) continue;
    let score = 1;
    if (p.brand === 'M&S') score += 5;
    if (p.packSizeDescription) score += 1;
    scored.push({ p, score, unit: unitAmt(p) });
  }
  scored.sort((a, b) => b.score - a.score || a.unit - b.unit);
  // dedupe identical product ids
  const seen = new Set();
  return scored.filter(({ p }) => !seen.has(p.retailerProductId) && seen.add(p.retailerProductId)).map(s => s.p);
}

const pickBest = (data, item, requireOrganic = false) => pickRanked(data, item, requireOrganic)[0] || null;

const products = {};
const organic = {};
const missed = [];
const names = Object.keys(OCADO_ITEMS);

const record = best => ({
  title: best.name,
  url: productUrl(best),
  size: best.packSizeDescription || null,
  perUnit: best.unitPrice?.price?.amount
    ? `£${best.unitPrice.price.amount} ${{ PER_1KG: 'per kg', PER_1L: 'per litre', PER_ITEM: 'each', PER_100G: 'per 100g' }[best.unitPrice.unitName] || ''}`.trim()
    : null,
  price: Number(best.price.amount),
});

for (const [i, name] of names.entries()) {
  const item = OCADO_ITEMS[name];
  const data = await searchApi(item.search);
  const ranked = data ? pickRanked(data, item) : [];
  const best = ranked[0];
  // the best organic option in the same results, for the "prefer organic" setting
  const organicBest = data && pickBest(data, item, true);
  if (organicBest) organic[name] = { ...record(organicBest), packGrams: packGrams(name, organicBest.packSizeDescription) };
  if (best) {
    products[name] = {
      ...record(best),
      packGrams: packGrams(name, best.packSizeDescription),
      // swap alternatives: the next two qualifying products
      alts: ranked.slice(1, 3).map(p => ({ ...record(p), packGrams: packGrams(name, p.packSizeDescription) })),
    };
    console.log(`[${i + 1}/${names.length}] ${name} → ${best.name} (${best.packSizeDescription ?? '?'}) £${best.price.amount}`);
  } else {
    missed.push(name);
    console.log(`[${i + 1}/${names.length}] ${name} → NO MATCH`);
  }
  await sleep(PAUSE_MS);
}

// Refuse to save a collapsed result set: if the site blocked us (as its bot
// defence does to datacenter IPs), overwriting the snapshot would wipe every
// price in the live app. Better to fail loudly and keep yesterday's data.
const MIN_PRODUCTS = 60;
if (Object.keys(products).length < MIN_PRODUCTS) {
  console.error(`\nOnly ${Object.keys(products).length} products matched (expected ~${names.length}).`);
  console.error('Refusing to overwrite the snapshot — the site probably blocked this run.');
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);
const out = `// Generated by scripts/ocado-fetch.mjs on ${today} — do not edit by hand.
// Refresh with: npm run ocado
export const OCADO_FETCHED_AT = '${today}';
export const OCADO_PRODUCTS = ${JSON.stringify(products, null, 2)};
// Best organic alternative per ingredient, used by the "prefer organic" setting.
export const OCADO_ORGANIC = ${JSON.stringify(organic, null, 2)};
`;
const dest = fileURLToPath(new URL('../src/ocado-products.js', import.meta.url));
writeFileSync(dest, out);
console.log(`\nWrote ${Object.keys(products).length}/${names.length} products to src/ocado-products.js`);
if (missed.length) console.log(`No match for: ${missed.join(', ')}`);
